_wandb:
    value:
        cli_version: 0.23.0
        e:
            ffzjoa0enfabsukjfh7e0rls8d6eu6jv:
                args:
                    - --model
                    - Qwen/Qwen3-4B
                    - --val-file
                    - pipeline_runs/auto/splits/train_data_rest_alpha_val.json
                    - --vector_path
                    - pipeline_runs/auto/artifacts/L14_N16/plausibility_layer14_last16_mc.pt
                    - --layer
                    - "14"
                    - --last_n
                    - "16"
                    - --alpha_min
                    - "-1.8"
                    - --alpha_max
                    - "-0.6"
                    - --alpha_steps
                    - "7"
                    - --objective
                    - accuracy
                    - --wandb-mode
                    - online
                    - --wandb-project
                    - semeval-task11
                    - --wandb-entity
                    - personal_rc
                    - --wandb-run-name
                    - sweep-qwen4b-mc-alpha-L14_N16
                codePath: scripts/search_alpha.py
                codePathLocal: scripts/search_alpha.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1073741824"
                        used: "11034624"
                email: choudharyramnarayan123@gmail.com
                executable: /home/ramnarayan.ramniwas/anaconda3/bin/python
                git:
                    commit: 98fe35d75ba369f8f8defbd16aa476eb9bc74fb0
                    remote: https://github.com/Ramnarayan-Choudhary/NLP_701.git
                gpu: NVIDIA RTX 5000 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-c2e1482c-7aeb-e910-bf53-6eaeaca40281
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-28306e01-bf49-bf05-b680-9b531d53c1d7
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-3905de69-0cb8-64ed-bdbd-22a57c08dac3
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-d9aff900-b0b6-2b18-10d7-89db70dd35b2
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-2873fcfc-cb9a-263b-df72-472ff61da06a
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-afd4705f-40f2-1857-fd9a-4a2980f47eec
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-c0a0a118-ac90-a626-16d5-b1a700889823
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-a333d841-10e7-c5c9-52b9-5e1ccd5fe21d
                host: gpu-01
                memory:
                    total: "811260125184"
                os: Linux-5.15.173-ql-generic-13.0-17-x86_64-with-glibc2.35
                program: /home/ramnarayan.ramniwas/MS_projects/NLP_701/scripts/search_alpha.py
                python: CPython 3.10.9
                root: /home/ramnarayan.ramniwas/MS_projects/NLP_701
                slurm:
                    cluster_name: zap
                    conf: /etc/qlustar/common/slurm-llnl/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x000000000000000000000000000000F0
                    cpu_bind_list: "0x000000000000000000000000000000F0"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: students
                    job_cpus_per_node: "4"
                    job_end_time: "1763913550"
                    job_gid: "2002"
                    job_group: students
                    job_id: "100679"
                    job_name: bash
                    job_nodelist: gpu-01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1763906350"
                    job_uid: "2875"
                    job_user: ramnarayan.ramniwas
                    jobid: "100679"
                    launch_node_ipaddr: 10.127.78.114
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu-01
                    nprocs: "1"
                    ntasks: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "41807"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "46385"
                    pty_win_col: "108"
                    pty_win_row: "16"
                    script_context: prolog_task
                    srun_comm_host: 10.127.78.114
                    srun_comm_port: "45535"
                    step_gpus: "1"
                    step_id: "0"
                    step_launcher_port: "45535"
                    step_nodelist: gpu-01
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/ramnarayan.ramniwas/MS_projects
                    submit_host: lo-01
                    task_pid: "1066981"
                    tasks_per_node: "1"
                    topology_addr: gpu-01
                    topology_addr_pattern: node
                    tres_per_task: cpu:4
                    umask: "0022"
                startedAt: "2025-11-23T14:31:58.743018Z"
                writerId: ffzjoa0enfabsukjfh7e0rls8d6eu6jv
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.10.9
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
alpha_max:
    value: -0.6
alpha_min:
    value: -1.8
alpha_steps:
    value: 7
last_n:
    value: 16
layer:
    value: 14
model:
    value: Qwen/Qwen3-4B
objective:
    value: accuracy
seed:
    value: 42
train_examples:
    value: 0
valid_examples:
    value: 95
valid_frac:
    value: 0.2
vector_path:
    value: pipeline_runs/auto/artifacts/L14_N16/plausibility_layer14_last16_mc.pt
